# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'navtool.ui'
#
# Created: Mon Dec  1 00:39:50 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(602, 197)
        MainWindow.setTabShape(QtGui.QTabWidget.Triangular)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 25))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtGui.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menuAnsicht = QtGui.QMenu(self.menubar)
        self.menuAnsicht.setObjectName("menuAnsicht")
        self.menuTabellen = QtGui.QMenu(self.menuAnsicht)
        self.menuTabellen.setObjectName("menuTabellen")
        self.menuLogs = QtGui.QMenu(self.menubar)
        self.menuLogs.setObjectName("menuLogs")
        self.menuViewer = QtGui.QMenu(self.menuLogs)
        self.menuViewer.setObjectName("menuViewer")
        self.menuHilfe = QtGui.QMenu(self.menubar)
        self.menuHilfe.setObjectName("menuHilfe")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_ffnen = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Test1/Downloads/icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ffnen.setIcon(icon)
        self.action_ffnen.setIconVisibleInMenu(True)
        self.action_ffnen.setObjectName("action_ffnen")
        self.actionBeenden = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Test1/Downloads/icons/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBeenden.setIcon(icon1)
        self.actionBeenden.setIconVisibleInMenu(True)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionHilfe_zu_den_Tools = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Test1/Downloads/icons/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHilfe_zu_den_Tools.setIcon(icon2)
        self.actionHilfe_zu_den_Tools.setIconVisibleInMenu(True)
        self.actionHilfe_zu_den_Tools.setObjectName("actionHilfe_zu_den_Tools")
        self.action_ber_das_NavTool = QtGui.QAction(MainWindow)
        self.action_ber_das_NavTool.setObjectName("action_ber_das_NavTool")
        self.actionLaserscanner = QtGui.QAction(MainWindow)
        self.actionLaserscanner.setObjectName("actionLaserscanner")
        self.actionBahnregler = QtGui.QAction(MainWindow)
        self.actionBahnregler.setObjectName("actionBahnregler")
        self.actionKonsistenzcheck = QtGui.QAction(MainWindow)
        self.actionKonsistenzcheck.setToolTip("Mit diesem Konsistenzcheck werden Reihen aus den CSV Dateien herausgefiltert, die nicht der korrekten Reihenlänge entsprechen.")
        self.actionKonsistenzcheck.setObjectName("actionKonsistenzcheck")
        self.actionSegment = QtGui.QAction(MainWindow)
        self.actionSegment.setObjectName("actionSegment")
        self.actionSegmente = QtGui.QAction(MainWindow)
        self.actionSegmente.setObjectName("actionSegmente")
        self.actionLaserscanner_2 = QtGui.QAction(MainWindow)
        self.actionLaserscanner_2.setObjectName("actionLaserscanner_2")
        self.actionTransponder = QtGui.QAction(MainWindow)
        self.actionTransponder.setObjectName("actionTransponder")
        self.actionSpeichern = QtGui.QAction(MainWindow)
        self.actionSpeichern.setObjectName("actionSpeichern")
        self.action_ber_den_Autor = QtGui.QAction(MainWindow)
        self.action_ber_den_Autor.setObjectName("action_ber_den_Autor")
        self.action_ber_QT = QtGui.QAction(MainWindow)
        self.action_ber_QT.setObjectName("action_ber_QT")
        self.menuDatei.addAction(self.action_ffnen)
        self.menuDatei.addAction(self.actionSpeichern)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionBeenden)
        self.menuTabellen.addAction(self.actionSegmente)
        self.menuTabellen.addAction(self.actionTransponder)
        self.menuTabellen.addAction(self.actionLaserscanner_2)
        self.menuAnsicht.addAction(self.menuTabellen.menuAction())
        self.menuAnsicht.addAction(self.actionSegment)
        self.menuViewer.addAction(self.actionLaserscanner)
        self.menuViewer.addAction(self.actionBahnregler)
        self.menuLogs.addAction(self.menuViewer.menuAction())
        self.menuLogs.addAction(self.actionKonsistenzcheck)
        self.menuHilfe.addAction(self.actionHilfe_zu_den_Tools)
        self.menuHilfe.addAction(self.action_ber_das_NavTool)
        self.menuHilfe.addAction(self.action_ber_den_Autor)
        self.menuHilfe.addAction(self.action_ber_QT)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menuAnsicht.menuAction())
        self.menubar.addAction(self.menuLogs.menuAction())
        self.menubar.addAction(self.menuHilfe.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionBeenden, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "NavTool", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatei.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAnsicht.setTitle(QtGui.QApplication.translate("MainWindow", "Ansicht", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTabellen.setTitle(QtGui.QApplication.translate("MainWindow", "Tabellen", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLogs.setTitle(QtGui.QApplication.translate("MainWindow", "Logs", None, QtGui.QApplication.UnicodeUTF8))
        self.menuViewer.setTitle(QtGui.QApplication.translate("MainWindow", "Viewer", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHilfe.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ffnen.setText(QtGui.QApplication.translate("MainWindow", "Öffnen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBeenden.setText(QtGui.QApplication.translate("MainWindow", "Beenden", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHilfe_zu_den_Tools.setText(QtGui.QApplication.translate("MainWindow", "Hilfe zu den Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ber_das_NavTool.setText(QtGui.QApplication.translate("MainWindow", "Über das NavTool", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLaserscanner.setText(QtGui.QApplication.translate("MainWindow", "Laserscanner", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBahnregler.setText(QtGui.QApplication.translate("MainWindow", "Bahnregler", None, QtGui.QApplication.UnicodeUTF8))
        self.actionKonsistenzcheck.setText(QtGui.QApplication.translate("MainWindow", "Konsistenzcheck", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSegment.setText(QtGui.QApplication.translate("MainWindow", "Segmente", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSegmente.setText(QtGui.QApplication.translate("MainWindow", "Segmente", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLaserscanner_2.setText(QtGui.QApplication.translate("MainWindow", "Lasermarken", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTransponder.setText(QtGui.QApplication.translate("MainWindow", "Transponder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpeichern.setText(QtGui.QApplication.translate("MainWindow", "Speichern", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ber_den_Autor.setText(QtGui.QApplication.translate("MainWindow", "Über den Autor", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ber_QT.setText(QtGui.QApplication.translate("MainWindow", "Über QT", None, QtGui.QApplication.UnicodeUTF8))

import navrc_rc
